// Generated migration page: React TSX converted from the approved static source.
import type { PageDefinition } from "@/content/types";

export const page = {"route":"about","title":"درباره بیوتی پی","description":"درباره پلتفرم بیوتی پی و مأموریت آن در صنعت مراقبت شخصی.","header":"consumer","pageKey":"about","bodyClasses":["has-standard-hero"],"data":{},"scripts":[],"redirectTo":null} as const satisfies PageDefinition;

export default function PageContent() { return <>
<main id={"main"}><section className={"hero lavender"}><div className={"container-xl px-3"}><div className={"small-caps"}>{"درباره ما"}</div><h1 className={"display-beautypay about-hero-title"}>{"فناوری مالی و رزرو برای چهار اکوسیستم خدماتی"}</h1><p className={"hero-sub mx-0"}>{"بیوتی پی مسیر کشف، رزرو و پرداخت اعتباری را برای خدمات سلامت، زیبایی، تندرستی و دندانپزشکی یکپارچه می‌کند و در سمت کسب‌وکار ابزار مدیریت مراجعه، فروش و رشد می‌دهد."}</p></div></section><div aria-label={"حوزه‌های تحت پوشش بیوتی پی"} className={"beautypay-sector-strip"}>
<article className={"beautypay-sector-item sector-health"}><div className={"beautypay-sector-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/sectors/health.avif"} type={"image/avif"} /><img alt={"فضای فوق‌واقعی خدمات سلامت"} decoding={"async"} fetchPriority={"high"} height={"400"} src={"/assets/images/sectors/health.webp"} width={"1200"} /><span className={"beautypay-sector-media-glow"}></span></picture></div><div className={"beautypay-sector-meta"}><div className={"beautypay-sector-icon"}><svg aria-hidden={"true"} fill={"none"} viewBox={"0 0 24 24"}><path d={"M12 21s-7-4.35-7-10.2A4.8 4.8 0 0 1 13.2 7.4L12 8.7l-1.2-1.3A4.8 4.8 0 0 1 19 10.8C19 16.65 12 21 12 21Z"} stroke={"currentColor"} strokeLinecap={"round"} strokeLinejoin={"round"} strokeWidth={"1.7"}></path><path d={"M9.2 12h1.8l.7-2.1 1.2 4.2.8-2.1h1.2"} stroke={"currentColor"} strokeLinecap={"round"} strokeLinejoin={"round"} strokeWidth={"1.7"}></path></svg></div><div className={"beautypay-sector-content"}><div className={"beautypay-sector-top"}><strong>{"سلامت"}</strong><span>{"HEALTH"}</span></div><p>{"پزشک، کلینیک، فیزیوتراپی و خدمات درمانی"}</p><small>{"پزشکی و درمان"}</small></div></div></article>
<article className={"beautypay-sector-item sector-beauty"}><div className={"beautypay-sector-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/sectors/beauty.avif"} type={"image/avif"} /><img alt={"فضای فوق‌واقعی خدمات زیبایی"} decoding={"async"} fetchPriority={"low"} height={"400"} loading={"lazy"} src={"/assets/images/sectors/beauty.webp"} width={"1200"} /></picture><span className={"beautypay-sector-media-glow"}></span></div><div className={"beautypay-sector-meta"}><div className={"beautypay-sector-icon"}><svg aria-hidden={"true"} fill={"none"} viewBox={"0 0 24 24"}><path d={"M12 3.5c1.25 3.85 3.4 6 7.25 7.25-3.85 1.25-6 3.4-7.25 7.25-1.25-3.85-3.4-6-7.25-7.25C8.6 9.5 10.75 7.35 12 3.5Z"} stroke={"currentColor"} strokeLinejoin={"round"} strokeWidth={"1.7"}></path><path d={"M18.5 3.5c.45 1.35 1.2 2.1 2.55 2.55-1.35.45-2.1 1.2-2.55 2.55-.45-1.35-1.2-2.1-2.55-2.55 1.35-.45 2.1-1.2 2.55-2.55Z"} stroke={"currentColor"} strokeLinejoin={"round"} strokeWidth={"1.5"}></path></svg></div><div className={"beautypay-sector-content"}><div className={"beautypay-sector-top"}><strong>{"زیبایی"}</strong><span>{"BEAUTY"}</span></div><p>{"سالن، پوست و مو، کلینیک زیبایی و ناخن"}</p><small>{"زیبایی و مراقبت"}</small></div></div></article>
<article className={"beautypay-sector-item sector-wellness"}><div className={"beautypay-sector-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/sectors/wellness.avif"} type={"image/avif"} /><img alt={"فضای فوق‌واقعی خدمات تندرستی"} decoding={"async"} fetchPriority={"low"} height={"400"} loading={"lazy"} src={"/assets/images/sectors/wellness.webp"} width={"1200"} /></picture><span className={"beautypay-sector-media-glow"}></span></div><div className={"beautypay-sector-meta"}><div className={"beautypay-sector-icon"}><svg aria-hidden={"true"} fill={"none"} viewBox={"0 0 24 24"}><path d={"M12 21c0-5.2 2.8-8.2 8-9-1.2 5.8-4.1 8.8-8 9Zm0 0c0-4.6-2.3-7.2-7-7.8.8 4.9 3.2 7.5 7 7.8Z"} stroke={"currentColor"} strokeLinecap={"round"} strokeLinejoin={"round"} strokeWidth={"1.7"}></path><path d={"M12 21V9.5"} stroke={"currentColor"} strokeLinecap={"round"} strokeWidth={"1.7"}></path><circle cx={"12"} cy={"5"} r={"2.5"} stroke={"currentColor"} strokeWidth={"1.7"}></circle></svg></div><div className={"beautypay-sector-content"}><div className={"beautypay-sector-top"}><strong>{"تندرستی"}</strong><span>{"WELLNESS"}</span></div><p>{"ماساژ، ورزش، تغذیه، ریکاوری و آرامش"}</p><small>{"سبک زندگی و ریکاوری"}</small></div></div></article>
<article className={"beautypay-sector-item sector-dental"}><div className={"beautypay-sector-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/sectors/dental.avif"} type={"image/avif"} /><img alt={"فضای فوق‌واقعی خدمات دندانپزشکی"} decoding={"async"} fetchPriority={"low"} height={"400"} loading={"lazy"} src={"/assets/images/sectors/dental.webp"} width={"1200"} /></picture><span className={"beautypay-sector-media-glow"}></span></div><div className={"beautypay-sector-meta"}><div className={"beautypay-sector-icon"}><svg aria-hidden={"true"} fill={"none"} viewBox={"0 0 24 24"}><path d={"M8.1 3.5c1.5 0 2.5.8 3.9.8s2.4-.8 3.9-.8c2.5 0 4.1 1.8 4.1 4.6 0 2.25-.7 3.6-1.55 5.2-.9 1.72-1.85 3.55-2.15 6.1-.12 1.02-.72 1.6-1.5 1.6-1.05 0-1.45-.85-1.78-2.3-.3-1.32-.55-2.45-1.02-2.45s-.72 1.13-1.02 2.45C10.65 20.15 10.25 21 9.2 21c-.78 0-1.38-.58-1.5-1.6-.3-2.55-1.25-4.38-2.15-6.1C4.7 11.7 4 10.35 4 8.1c0-2.8 1.6-4.6 4.1-4.6Z"} stroke={"currentColor"} strokeLinejoin={"round"} strokeWidth={"1.7"}></path></svg></div><div className={"beautypay-sector-content"}><div className={"beautypay-sector-top"}><strong>{"دندانپزشکی"}</strong><span>{"DENTAL"}</span></div><p>{"مطب، کلینیک، ارتودنسی، ایمپلنت و زیبایی دندان"}</p><small>{"درمان و زیبایی دندان"}</small></div></div></article>
</div><section className={"section"}><div className={"container-xl px-3"}><div className={"row g-5 align-items-center"}><div className={"col-lg-6"}><img alt={"تیم و کسب‌وکارها"} className={"rounded-5"} decoding={"async"} fetchPriority={"low"} height={"1024"} loading={"lazy"} src={"/assets/images/photoreal/team.webp"} width={"1536"} /></div><div className={"col-lg-6"}><h2 className={"section-title"}>{"یک تجربه مشترک برای بیمار، مراجعه‌کننده و کسب‌وکار"}</h2><p className={"section-lead"}>{"بیمار و مراجعه‌کننده باید پزشک، دندانپزشک، سالن یا مرکز تندرستی مناسب را پیدا کند و هزینه را مدیریت‌پذیر بپردازد؛ در سوی دیگر، کسب‌وکار به تقویم، CRM، پرداخت اعتباری، تسویه و رشد نیاز دارد. بیوتی پی این دو جریان را به هم متصل می‌کند."}</p></div></div></div></section></main>
</>; }
