// Generated migration page: React TSX converted from the approved static source.
import type { PageDefinition } from "@/content/types";

export const page = {"route":"accelerate","title":"کمپین رشد · Accelerate | بیوتی پی","description":"Accelerate بیوتی پی؛ چهار مسیر شتاب‌دهی به رشد و درآمد کسب‌وکارهای سلامت، زیبایی، تندرستی و دندانپزشکی.","header":"business","pageKey":"accelerate","bodyClasses":["has-standard-hero","acc-page"],"data":{},"scripts":[],"redirectTo":null} as const satisfies PageDefinition;

export default function PageContent() { return <>
<main id={"main"}><section className={"acc-hero"}><div className={"container-xl px-3"}><div className={"row align-items-center g-5"}><div className={"col-lg-6"}><span className={"acc-eyebrow"}>{"ACCELERATE · کمپین رشد"}</span><h1 className={"acc-title"}>{"۴ روش برای شتاب‌دهی به رشد و درآمد شما"}</h1><p className={"acc-lead"}>{"Accelerate لایه رشد بیوتی پی برای مطب، کلینیک، سالن و مراکز تندرستی است؛ ترکیبی از اعتبار، رسانه، ارتباط مستقیم و دسترسی به شبکه‌های بزرگ کاربری برای اینکه مشتری قبلی دوباره برگردد و مشتری جدید سریع‌تر شما را پیدا کند."}</p><div className={"d-flex flex-wrap gap-2 mt-4"}><a className={"btn-f btn-f-dark"} href={"#methods"}>{"مشاهده ۴ روش رشد"}</a><a className={"btn-f btn-f-light"} href={"#accelerate-form"}>{"درخواست اجرای کمپین"}</a></div><div className={"acc-stat-grid"}><div className={"acc-stat"}><strong>{"۱٬۰۰۰ مشتری"}</strong><span>{"ظرفیت شروع کمپین اعتباری CRM"}</span></div><div className={"acc-stat"}><strong>{"۲۰M+ کاربر"}</strong><span>{"دسترسی از مسیر سوپراپ‌ها"}</span></div><div className={"acc-stat"}><strong>{"هزاران کارمند"}</strong><span>{"شبکه سازمانی و شرکتی قابل هدف‌گیری"}</span></div></div></div><div className={"col-lg-6"}><div className={"acc-hero-art"}><img src={"/assets/images/illustrations/gift-card-clinic-redesign.png"} width={"1672"} height={"941"} alt={"کمپین رشد بیوتی پی و کارت‌های اعتباری مشتریان"} fetchPriority={"high"} decoding={"async"} /></div></div></div></div></section>
<section className={"acc-section"} id={"methods"}><div className={"container-xl px-3"}><div className={"acc-heading"}><span className={"acc-eyebrow"}>{"۴ موتور رشد"}</span><h2 className={"mt-3"}>{"از CRM خودتان شروع کنید؛ بعد به میلیون‌ها کاربر برسید"}</h2><p>{"هر روش می‌تواند مستقل اجرا شود یا در قالب یک کمپین ترکیبی کنار بقیه قرار بگیرد. هدف این است که هم نرخ بازگشت مشتریان قبلی افزایش پیدا کند و هم ظرفیت جذب مشتری جدید از کانال‌های بزرگ فعال شود."}</p></div><div className={"acc-grid"}>
<article className={"acc-card"}><div className={"acc-card-num"}>{"۱"}</div><h3>{"تخصیص اعتبار به مشتریان قبلی CRM شما"}</h3><p>{"لیست مشتریان قبلی کسب‌وکار شما به یک کمپین بازگشت تبدیل می‌شود. بر اساس قواعد توافق‌شده، برای مشتریان واجد شرایط اعتبار خرید تعریف می‌شود تا مانع بودجه در تصمیم مراجعه کمتر شود."}</p><ul><li>{"امکان شروع با ۱٬۰۰۰ مشتری منتخب"}</li><li>{"ترکیب اعتبارهای ۱۰، ۲۰، ۳۰، ۵۰ و ۱۰۰ میلیون تومانی"}</li><li>{"سگمنت‌بندی بر اساس سابقه مراجعه و ارزش مشتری"}</li></ul></article>
<article className={"acc-card"}><div className={"acc-card-num"}>{"۲"}</div><h3>{"درج بنر کسب‌وکار در اپلیکیشن بیوتی پی"}</h3><p>{"کسب‌وکار و پیشنهاد ویژه شما در جایگاه‌های تبلیغاتی اپلیکیشن و صفحات کشف سرویس نمایش داده می‌شود تا در معرض دید کاربران بیشتری قرار بگیرید."}</p><ul><li>{"بنر و جایگاه ویژه در صفحات مرتبط"}</li><li>{"هدایت مستقیم به پروفایل، خدمت یا رزرو"}</li><li>{"قابل هدف‌گیری بر اساس حوزه خدمت و موقعیت"}</li></ul></article>
<article className={"acc-card"}><div className={"acc-card-num"}>{"۳"}</div><h3>{"کمپین مشترک پیامکی، بنری و تماس تلفنی هوشمند"}</h3><p>{"برای یک پیشنهاد مشخص، چند کانال را هم‌زمان فعال می‌کنیم؛ پیامک برای دسترسی سریع، بنر برای یادآوری و تماس هوشمند برای تبدیل لیدهایی که نیاز به توضیح یا پیگیری دارند."}</p><ul><li>{"سناریوی چندمرحله‌ای جذب و فالوآپ"}</li><li>{"پیام و پیشنهاد مشترک با برند کسب‌وکار"}</li><li>{"اندازه‌گیری ورودی، رزرو و تبدیل کمپین"}</li></ul></article>
<article className={"acc-card"}><div className={"acc-card-num"}>{"۴"}</div><h3>{"معرفی مرکز و خدمات به بیش از ۲۰ میلیون کاربر سوپراپ‌ها"}</h3><p>{"با استفاده از ظرفیت شبکه‌های همکار و سوپراپلیکیشن‌ها، خدمات شما می‌تواند به جامعه کاربری بزرگ‌تری در تارا، وایب و کیپا معرفی شود و مسیر دسترسی کاربر به رزرو یا خرید کوتاه‌تر شود."}</p><ul><li>{"نمایش پیشنهاد خدمت در کانال‌های شریک"}</li><li>{"کمپین‌های مناسبتی یا دسته‌بندی‌شده"}</li><li>{"اتصال پیشنهاد به اعتبار و روش پرداخت"}</li></ul></article>
</div></div></section>
<section className={"acc-section pt-0"}><div className={"container-xl px-3"}><div className={"acc-org"}><div><span className={"acc-eyebrow"}>{"ORGANIZATIONAL REACH"}</span><h2 className={"mt-3"}>{"دسترسی به هزاران کارمند سازمانی و شرکتی"}</h2><p>{"بیوتی پی می‌تواند در قالب همکاری‌های سازمانی، خدمات شما را به کارکنان شرکت‌ها و سازمان‌های طرف همکاری معرفی کند؛ جامعه‌ای که معمولاً نیاز مشخص، قدرت خرید قابل‌پیش‌بینی و امکان استفاده از بسته‌های اعتباری یا رفاهی دارد. برای هر سازمان می‌توان پیشنهاد اختصاصی، کد کمپین، صفحه فرود و مسیر رزرو مستقل تعریف کرد."}</p></div><div className={"acc-org-stats"}><div className={"acc-org-stat"}><strong>{"سازمانی"}</strong><span>{"کمپین متناسب با مزایای کارکنان"}</span></div><div className={"acc-org-stat"}><strong>{"قابل اندازه‌گیری"}</strong><span>{"لید، رزرو و فروش هر کانال"}</span></div><div className={"acc-org-stat"}><strong>{"چندکاناله"}</strong><span>{"پیامک، بنر، تماس و اپ"}</span></div><div className={"acc-org-stat"}><strong>{"اعتباری"}</strong><span>{"اتصال مستقیم به روش پرداخت"}</span></div></div></div></div></section>
<section className={"acc-section pt-0"} id={"accelerate-form"}><div className={"container-xl px-3"}><div className={"row g-4 align-items-start"}><div className={"col-lg-5"}><div className={"acc-heading mb-0"}><span className={"acc-eyebrow"}>{"شروع کمپین"}</span><h2 className={"mt-3"}>{"ترکیب مناسب برای کسب‌وکار شما را طراحی کنیم"}</h2><p>{"اطلاعات پایه را بفرستید؛ کارشناس رشد بیوتی پی برای انتخاب مخاطب، پیشنهاد اعتباری و کانال‌های مناسب با شما تماس می‌گیرد."}</p></div></div><div className={"col-lg-7"}><form className={"acc-form"} data-sales-form={""}><div className={"row g-3"}><div className={"col-md-6"}><label className={"form-label"}>{"نام مدیر"}</label><input className={"form-control"} name={"name"} required={true} /></div><div className={"col-md-6"}><label className={"form-label"}>{"شماره موبایل"}</label><input className={"form-control"} name={"mobile"} inputMode={"tel"} placeholder={"۰۹۱۲۱۲۳۴۵۶۷"} required={true} /></div><div className={"col-md-6"}><label className={"form-label"}>{"نام کسب‌وکار"}</label><input className={"form-control"} name={"business"} required={true} /></div><div className={"col-md-6"}><label className={"form-label"}>{"حوزه فعالیت"}</label><select className={"form-select"} name={"sector"}><option>{"سلامت"}</option><option>{"زیبایی"}</option><option>{"تندرستی"}</option><option>{"دندانپزشکی"}</option></select></div><div className={"col-12"}><label className={"form-label d-block"}>{"روش‌های موردنظر"}</label><div className={"acc-method-pills"}><label><input type={"checkbox"} defaultChecked={true} /><span>{"اعتبار CRM"}</span></label><label><input type={"checkbox"} /><span>{"بنر اپ"}</span></label><label><input type={"checkbox"} /><span>{"کمپین مشترک"}</span></label><label><input type={"checkbox"} /><span>{"سوپراپ‌ها"}</span></label><label><input type={"checkbox"} /><span>{"جامعه سازمانی"}</span></label></div></div><div className={"col-12"}><button className={"btn-f btn-f-dark w-100"} type={"submit"}>{"ثبت درخواست Accelerate"}</button></div></div></form></div></div></div></section></main>
</>; }
