// Generated migration page: React TSX converted from the approved static source.
import type { PageDefinition } from "@/content/types";

export const page = {"route":"commission","title":"کارمزد · Commission | بیوتی پی","description":"Commission بیوتی پی؛ مقایسه کارمزد و زمان تسویه سرویس‌های پرداخت اعتباری و شرایط تسویه بیوتی پی.","header":"business","pageKey":"commission","bodyClasses":["has-standard-hero","cm-page"],"data":{},"scripts":[],"redirectTo":null} as const satisfies PageDefinition;

export default function PageContent() { return <>
<main id={"main"}><section className={"cm-hero"}><div className={"container-xl px-3"}><span className={"cm-kicker"}>{"COMMISSION · کارمزد"}</span><h1 className={"cm-title"}>{"مقایسه کارمزد و زمان تسویه سرویس‌های پرداخت اعتباری"}</h1><p className={"cm-lead"}>{"برای تصمیم‌گیری کسب‌وکار، فقط درصد کارمزد مهم نیست؛ زمان تسویه، مدل وصول اقساط و سرعت برگشت سرمایه هم روی حاشیه سود اثر دارد. این جدول یک مقایسه عملی از سرویس‌های اعتباری متصل به اکوسیستم بیوتی پی ارائه می‌کند."}</p><div className={"cm-summary"}><div><strong>{"۱۲ سرویس"}</strong><span>{"پرداخت اعتباری و اقساطی"}</span></div><div><strong>{"۱۰٪ تا ۱۵٪"}</strong><span>{"بازه کارمزد سناریوهای بیوتی پی"}</span></div><div><strong>{"۷ / ۳۰ / ۶۵ روز"}</strong><span>{"گزینه‌های تسویه بیوتی پی"}</span></div></div></div></section><section className={"pb-5"}><div className={"container-xl px-3"}><div className={"cm-table-shell table-responsive"}><table className={"table cm-table align-middle"}><thead><tr><th>{"سرویس"}</th><th>{"کارمزد سرویس"}</th><th>{"کارمزد بیوتی پی"}</th><th>{"تسویه سرویس"}</th><th>{"تسویه بیوتی پی"}</th></tr></thead><tbody><tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/dimapay.svg"} alt={"لوگوی دیماپی"} loading={"lazy"} decoding={"async"} /></div><strong>{"دیماپی"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"14%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"10%"}</span></td><td>{"ماهیانه هر قسط"}</td><td><strong>{"7 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/snapppay.svg"} alt={"لوگوی اسنپ‌پی"} loading={"lazy"} decoding={"async"} /></div><strong>{"اسنپ‌پی"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"20%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"15%"}</span></td><td>{"2 ماهه"}</td><td><strong>{"30 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/digipay.svg"} alt={"لوگوی دیجی‌پی"} loading={"lazy"} decoding={"async"} /></div><strong>{"دیجی‌پی"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"18%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"14%"}</span></td><td>{"ماهیانه هر قسط"}</td><td><strong>{"30 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/tara.svg"} alt={"لوگوی تارا"} loading={"lazy"} decoding={"async"} /></div><strong>{"تارا"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"16%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"12%"}</span></td><td>{"2 ماهه"}</td><td><strong>{"7 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/keepa.svg"} alt={"لوگوی کیپا"} loading={"lazy"} decoding={"async"} /></div><strong>{"کیپا"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"15%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"11%"}</span></td><td>{"ماهیانه هر قسط"}</td><td><strong>{"7 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/azkivam.svg"} alt={"لوگوی ازکی‌وام"} loading={"lazy"} decoding={"async"} /></div><strong>{"ازکی‌وام"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"18%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"13%"}</span></td><td>{"2 ماهه"}</td><td><strong>{"30 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/bajet.svg"} alt={"لوگوی باجت"} loading={"lazy"} decoding={"async"} /></div><strong>{"باجت"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"17%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"13%"}</span></td><td>{"ماهیانه هر قسط"}</td><td><strong>{"30 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/vibe.svg"} alt={"لوگوی وایب"} loading={"lazy"} decoding={"async"} /></div><strong>{"وایب"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"14%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"10%"}</span></td><td>{"2 ماهه"}</td><td><strong>{"7 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/vipad.svg"} alt={"لوگوی ویپاد"} loading={"lazy"} decoding={"async"} /></div><strong>{"ویپاد"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"17%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"12%"}</span></td><td>{"ماهیانه هر قسط"}</td><td><strong>{"30 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/technopay.svg"} alt={"لوگوی تکنوپی"} loading={"lazy"} decoding={"async"} /></div><strong>{"تکنوپی"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"15%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"11%"}</span></td><td>{"2 ماهه"}</td><td><strong>{"30 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/kalapay.svg"} alt={"لوگوی کالاپی"} loading={"lazy"} decoding={"async"} /></div><strong>{"کالاپی"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"16%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"12%"}</span></td><td>{"ماهیانه هر قسط"}</td><td><strong>{"65 روزه"}</strong></td></tr>
<tr><td><div className={"cm-brand"}><div className={"cm-logo"}><img src={"/assets/images/payment-providers/torobpay.svg"} alt={"لوگوی ترب‌پی"} loading={"lazy"} decoding={"async"} /></div><strong>{"ترب‌پی"}</strong></div></td><td><span className={"cm-rate cm-rate-market"}>{"12%"}</span></td><td><span className={"cm-rate cm-rate-us"}>{"10%"}</span></td><td>{"2 ماهه"}</td><td><strong>{"30 روزه"}</strong></td></tr></tbody></table></div><div className={"cm-note"}><strong>{"نکته درباره نرخ‌ها:"}</strong>{" کارمزد دقیق پذیرندگی در بسیاری از سرویس‌ها عمومی و ثابت نیست و می‌تواند بر اساس صنف، حجم فروش، مدل اعتباری و قرارداد تغییر کند. اعداد ستون «کارمزد سرویس» در این صفحه به‌عنوان نرخ مرجع/سناریوی مقایسه‌ای در بازه درخواستی ۱۲ تا ۲۰ درصد درج شده‌اند و برای انتشار قراردادی باید با آخرین قرارداد فعال همان سرویس تطبیق داده شوند."}</div></div></section><section className={"cm-why"}><div className={"container-xl px-3"}><div className={"row g-4 align-items-center"}><div className={"col-lg-5"}><div className={"cm-settle"}><div className={"small-caps text-white-50"}>{"تسویه منعطف"}</div><h2 className={"mt-2"}>{"پول فروش را متناسب با نیاز نقدینگی دریافت کنید"}</h2><p>{"به‌جای انتظار برای وصول همه اقساط، مدل تسویه بیوتی پی می‌تواند بر اساس قرارداد در یکی از سیکل‌های ۷، ۳۰ یا ۶۵ روزه تنظیم شود."}</p><div className={"cm-settle-badges"}><span>{"تسویه ۷ روزه"}</span><span>{"تسویه ۳۰ روزه"}</span><span>{"تسویه ۶۵ روزه"}</span></div></div></div><div className={"col-lg-7"}><div className={"cm-why-grid"}><article className={"cm-why-card"}><h3>{"مقایسه شفاف"}</h3><p>{"در یک نگاه ببینید هر سرویس چه ساختار کارمزد و تسویه‌ای دارد."}</p></article><article className={"cm-why-card"}><h3>{"انتخاب بر اساس نقدینگی"}</h3><p>{"سرویس را فقط بر اساس درصد انتخاب نکنید؛ زمان برگشت پول را هم وارد تصمیم کنید."}</p></article><article className={"cm-why-card"}><h3>{"چند سرویس در یک اتصال"}</h3><p>{"کسب‌وکار می‌تواند به‌جای مذاکره و اتصال جداگانه، از مسیر یکپارچه استفاده کند."}</p></article></div></div></div></div></section></main>
</>; }
