// Generated migration page: React TSX converted from the approved static source.
import type { PageDefinition } from "@/content/types";

export const page = {"route":"connect","title":"دایرکت هوشمند · Connect | بیوتی پی","description":"Connect بیوتی پی؛ دایرکت هوشمند برای پاسخ خودکار به پیام و کامنت، فرم، ویترین خدمات، فالوآپ و جمع‌آوری لید.","header":"business","pageKey":"connect","bodyClasses":["has-standard-hero","cn-page"],"data":{},"scripts":[],"redirectTo":null} as const satisfies PageDefinition;

export default function PageContent() { return <>
<main id={"main"}><section className={"cn-hero"}><div className={"container-xl px-3 position-relative"}><div className={"row align-items-center g-5"}><div className={"col-lg-6"}><div className={"cn-kicker"}>{"CONNECT · دایرکت هوشمند"}</div><h1 className={"cn-title"}>{"کامنت و دایرکت را به مسیر فروش و رزرو تبدیل کنید"}</h1><p className={"cn-lead"}>{"برای پیام‌ها و کامنت‌های پرتکرار سناریو بسازید، پاسخ فوری بفرستید، فرم و ویترین خدمات نمایش دهید و فالوآپ را خودکار کنید؛ بدون اینکه تیم شما تمام روز درگیر پاسخ‌های تکراری باشد."}</p><div className={"d-flex flex-wrap gap-2 mt-4"}><a className={"btn-f btn-f-light"} href={"#features"}>{"مشاهده امکانات"}</a><a className={"btn-f btn-f-dark"} href={"#start"}>{"درخواست فعال‌سازی"}</a></div><div className={"cn-chips"}><span className={"cn-chip"}>{"پاسخ خودکار دایرکت"}</span><span className={"cn-chip"}>{"کامنت هوشمند"}</span><span className={"cn-chip"}>{"فرم‌ساز"}</span><span className={"cn-chip"}>{"فالوآپ"}</span><span className={"cn-chip"}>{"ویترین خدمات"}</span></div></div><div className={"col-lg-6"}><div className={"cn-hero-img"}><img src={"/assets/images/photoreal/connect-hero.webp"} width={"1536"} height={"1024"} alt={"دایرکت هوشمند بیوتی پی Connect"} fetchPriority={"high"} decoding={"async"} /></div></div></div></div></section>
<section className={"cn-section"} id={"features"}><div className={"container-xl px-3"}><div className={"cn-heading"}><div className={"small-caps text-muted"}>{"امکانات Connect"}</div><h2>{"یک اتوماسیون کامل برای گفت‌وگوی اینستاگرامی کسب‌وکار"}</h2><p>{"امکانات زیر با تمرکز بر نیاز مراکز سلامت، زیبایی، تندرستی و دندانپزشکی بازطراحی شده‌اند تا پاسخ، لید، معرفی خدمت و پیگیری مشتری در یک مسیر منظم انجام شود."}</p></div><div className={"cn-grid"}>
<article className={"cn-card"}><div className={"cn-icon"}>{"01"}</div><h3>{"پاسخ خودکار به دایرکت"}</h3><p>{"با تعریف کلمه یا عبارت، پیام مناسب بلافاصله ارسال می‌شود؛ از قیمت خدمت تا لینک رزرو و اطلاعات شعبه."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"02"}</div><h3>{"پاسخ خودکار به کامنت"}</h3><p>{"کامنت‌های زیر پست یا لایو می‌توانند به‌صورت خودکار یک سناریوی دایرکت را فعال کنند."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"03"}</div><h3>{"پاسخ هم‌زمان در کامنت"}</h3><p>{"پس از ارسال پاسخ خصوصی، یک پاسخ عمومی هم زیر کامنت درج می‌شود تا تعامل پست حفظ شود."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"04"}</div><h3>{"سناریوساز و کلمه کلیدی"}</h3><p>{"برای هر سؤال، خدمت یا کمپین مسیر جدا تعریف کنید و کاربر را مرحله‌به‌مرحله به رزرو یا درخواست مشاوره برسانید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"05"}</div><h3>{"ویترین خدمات و محصولات"}</h3><p>{"خدمت‌ها، پکیج‌ها یا محصولات را به‌صورت اسلایدی و قابل انتخاب داخل دایرکت نمایش دهید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"06"}</div><h3>{"فرم‌ساز هوشمند"}</h3><p>{"برای مشاوره، رزرو، سفارش، نظرسنجی یا ارزیابی اولیه فرم بسازید و پاسخ‌ها را ساختاریافته دریافت کنید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"07"}</div><h3>{"شرط فالو"}</h3><p>{"در سناریوهای بازاریابی می‌توانید ارسال محتوای خاص را به فالو بودن کاربر وابسته کنید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"08"}</div><h3>{"پیام یادآوری و فالوآپ"}</h3><p>{"بعد از زمان مشخص، پیام پیگیری برای تکمیل رزرو، استفاده از پیشنهاد یا ادامه مشاوره ارسال شود."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"09"}</div><h3>{"پاسخ با محتوای متنوع"}</h3><p>{"متن، تصویر، ویس، دکمه، لینک رزرو و کارت خدمت را داخل سناریوهای پاسخ قرار دهید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"10"}</div><h3>{"جمع‌آوری شماره و لید"}</h3><p>{"اطلاعات تماس دریافت‌شده در دایرکت را برای پیگیری و کمپین‌های بعدی ساختاریافته نگه دارید و خروجی بگیرید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"11"}</div><h3>{"سؤالات متداول"}</h3><p>{"پاسخ سؤال‌های تکراری مثل قیمت، ساعات کاری، شرایط پرداخت و آمادگی قبل از خدمت را آماده کنید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"12"}</div><h3>{"منوی سریع"}</h3><p>{"منوی دکمه‌ای برای «رزرو»، «خدمات»، «اعتبار»، «لوکیشن» و «پشتیبانی» بسازید تا کاربر سریع‌تر جلو برود."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"13"}</div><h3>{"دستور اختصاصی هر پست"}</h3><p>{"برای یک پست یا کمپین مشخص، کلمات و پاسخ‌های مخصوص همان محتوا را فعال کنید."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"14"}</div><h3>{"راه‌اندازی بدون دانش فنی"}</h3><p>{"سناریوها با تنظیمات ساده ساخته می‌شوند و نیاز به برنامه‌نویسی برای پاسخ‌های روزمره ندارند."}</p></article>
<article className={"cn-card"}><div className={"cn-icon"}>{"15"}</div><h3>{"اتصال امن و بدون پسورد"}</h3><p>{"اتصال حساب از مسیر رسمی API انجام می‌شود و نیازی به تحویل رمز عبور اینستاگرام به سرویس نیست."}</p></article>
</div></div></section>
<section className={"cn-section cn-flow"}><div className={"container-xl px-3"}><div className={"cn-heading"}><div className={"small-caps text-muted"}>{"FLOW"}</div><h2>{"یک مسیر نمونه برای تبدیل کامنت به رزرو"}</h2></div><div className={"cn-flow-grid"}><div className={"cn-step"}><span className={"cn-step-num"}>{"01"}</span><strong>{"کامنت کاربر"}</strong><p>{"کاربر زیر پست می‌نویسد «قیمت» یا «رزرو»."}</p></div><div className={"cn-step"}><span className={"cn-step-num"}>{"02"}</span><strong>{"دایرکت خودکار"}</strong><p>{"Connect اطلاعات خدمت یا منوی انتخاب را می‌فرستد."}</p></div><div className={"cn-step"}><span className={"cn-step-num"}>{"03"}</span><strong>{"فرم و لید"}</strong><p>{"نام، موبایل، خدمت و شعبه موردنظر دریافت می‌شود."}</p></div><div className={"cn-step"}><span className={"cn-step-num"}>{"04"}</span><strong>{"پیگیری"}</strong><p>{"لینک رزرو، یادآوری و در صورت نیاز انتقال به کارشناس انجام می‌شود."}</p></div></div></div></section>
<section className={"cn-section"}><div className={"container-xl px-3"}><div className={"cn-use"}><div className={"cn-use-card"}><h3>{"برای فروش و رزرو"}</h3><p>{"Connect می‌تواند فاصله بین سؤال ساده و اقدام واقعی را کوتاه کند."}</p><ul className={"cn-list"}><li>{"معرفی خدمات و قیمت‌های قابل انتشار"}</li><li>{"ارسال لینک رزرو یا صفحه پرداخت"}</li><li>{"جمع‌آوری لید برای مشاوره تلفنی"}</li><li>{"فالوآپ پیشنهادهای محدود زمانی"}</li></ul></div><div className={"cn-use-card"}><h3>{"برای خدمات مشتری"}</h3><p>{"اطلاعات پرتکرار را استاندارد کنید و تیم را از پاسخ‌های تکراری آزاد کنید."}</p><ul className={"cn-list"}><li>{"ساعات کاری و آدرس شعب"}</li><li>{"شرایط قبل و بعد از مراجعه"}</li><li>{"پاسخ به سؤالات پرداخت اعتباری"}</li><li>{"ارجاع سؤال حساس به نیروی انسانی"}</li></ul></div></div><div className={"cn-secure mt-4"}><div className={"row align-items-center g-3"}><div className={"col-lg-8"}><strong className={"fs-5 d-block mb-1"}>{"امنیت اتصال"}</strong><span className={"text-muted"}>{"حساب اینستاگرام از مسیر رسمی API متصل می‌شود؛ طراحی سرویس بر مبنای عدم دریافت پسورد و مدیریت سناریوها از پنل انجام شده است."}</span></div><div className={"col-lg-4 text-lg-end"}><a className={"btn-f btn-f-dark"} href={"#start"}>{"فعال‌سازی Connect"}</a></div></div></div></div></section>
<section className={"cn-section pt-0"} id={"start"}><div className={"container-xl px-3"}><div className={"row g-5"}><div className={"col-lg-5"}><div className={"cn-heading"}><div className={"small-caps text-muted"}>{"شروع سریع"}</div><h2>{"اولین سناریو را با یک کامنت ساده شروع کنید"}</h2><p>{"اکانت، نوع کسب‌وکار و سناریوی اصلی خود را مشخص کنید تا مسیر فعال‌سازی و تنظیم اولیه آماده شود."}</p></div></div><div className={"col-lg-7"}><form className={"cn-form"} data-sales-form={""}><div className={"row g-3"}><div className={"col-md-6"}><label className={"form-label"}>{"نام کسب‌وکار"}</label><input className={"form-control"} name={"business"} required={true} /></div><div className={"col-md-6"}><label className={"form-label"}>{"شماره موبایل مدیر"}</label><input className={"form-control"} name={"mobile"} required={true} inputMode={"tel"} /></div><div className={"col-md-6"}><label className={"form-label"}>{"آیدی اینستاگرام"}</label><input className={"form-control"} name={"instagram"} placeholder={"@yourpage"} /></div><div className={"col-md-6"}><label className={"form-label"}>{"هدف اصلی"}</label><select className={"form-select"}><option>{"رزرو و فروش"}</option><option>{"جمع‌آوری لید"}</option><option>{"پشتیبانی"}</option><option>{"کمپین کامنت"}</option></select></div><div className={"col-12"}><button className={"btn-f btn-f-dark w-100"} type={"submit"}>{"درخواست راه‌اندازی Connect"}</button></div></div></form></div></div></div></section>
<section className={"cn-section pt-0"}><div className={"container-xl px-3"}><div className={"cn-heading"}><div className={"small-caps text-muted"}>{"FAQ"}</div><h2>{"پرسش‌های متداول"}</h2></div><div className={"cn-faq"}><details><summary>{"آیا برای اتصال اینستاگرام باید پسورد بدهیم؟"}</summary><p>{"خیر. اتصال از مسیر رسمی API انجام می‌شود و مدل سرویس بر پایه دریافت نکردن پسورد اکانت طراحی شده است."}</p></details><details><summary>{"آیا می‌توان برای هر پست پاسخ متفاوت داشت؟"}</summary><p>{"بله؛ برای هر پست، کمپین یا کلمه کلیدی می‌توانید سناریوی مخصوص تعریف کنید."}</p></details><details><summary>{"آیا اطلاعات کاربران قابل خروجی است؟"}</summary><p>{"اطلاعاتی که کاربر در فرم‌ها و مسیرهای مجاز وارد می‌کند می‌تواند برای پیگیری و گزارش ساختاریافته شود."}</p></details><details><summary>{"Connect جای ادمین را می‌گیرد؟"}</summary><p>{"هدف حذف ارتباط انسانی نیست؛ پاسخ‌های تکراری خودکار می‌شوند و موارد حساس، پیچیده یا فروش جدی می‌توانند به کارشناس ارجاع شوند."}</p></details></div></div></section></main>
</>; }
