// Generated migration page: React TSX converted from the approved static source.
import type { PageDefinition } from "@/content/types";

export const page = {"route":"suppliers","title":"تأمین‌کنندگان عمده بیوتی پی — B2B و SCF","description":"تأمین‌کنندگان عمده بیوتی پی؛ خرید B2B تجهیزات و اقلام سلامت، زیبایی، تندرستی و دندانپزشکی با پرداخت نقدی، آنلاین و اعتبار SCF برای کالاهای منتخب.","header":"business","pageKey":"suppliers","bodyClasses":["suppliers-page","has-standard-hero"],"data":{},"scripts":["/legacy/pages/suppliers.js"],"redirectTo":null} as const satisfies PageDefinition;

export default function PageContent() { return <>
<main id={"main"}>
<section className={"sup-hero"}><div className={"container-xl px-3"}><div className={"sup-hero-grid"}><div><span className={"sup-kicker"}><span className={"sup-kicker-dot"}></span>{" بازار عمده کسب‌وکارهای بیوتی پی"}</span><h1>{"تأمین‌کننده، برند و کالای عمده؛ با امکان خرید "}<span className={"scf-word"}>{"SCF"}</span>{"."}</h1><p>{"برای مطب، کلینیک، سالن، مرکز زیبایی، باشگاه و کسب‌وکارهای سلامت و تندرستی. شرکت‌های تولیدکننده، واردکننده، توزیع‌کننده و عمده‌فروش را بر اساس حوزه فعالیت، برندهای تحت پوشش، تعداد اقلام و شرایط تسویه مقایسه کنید."}</p><form className={"sup-search"} id={"supSearch"}><input aria-label={"جست‌وجوی نام شرکت، برند، کالا یا کد SKU"} autoComplete={"off"} id={"supSearchInput"} name={"supplier_search"} placeholder={"نام شرکت، برند، کالا یا کد SKU را جست‌وجو کنید…"} type={"search"} /><button type={"submit"}>{"جست‌وجوی عمده"}</button></form><div className={"sup-hero-chips"}><span>{"نقدی"}</span><span>{"پرداخت آنلاین"}</span><span>{"اعتباری فقط SCF"}</span><span>{"کد اختصاصی هر کالا"}</span><span>{"حداقل سفارش و موجودی شفاف"}</span></div></div>
<div className={"sup-hero-panel"}><div className={"sup-panel-top"}><div><div className={"sup-panel-title"}>{"خرید با اعتبار زنجیره تأمین"}</div><div className={"sup-panel-sub"}>{"فقط کالاهای دارای نشان سبز SCF"}</div></div><span className={"sup-scf-badge-lg"}>{"SCF"}</span></div><div className={"sup-flow"}><div className={"sup-flow-step"}><span className={"sup-flow-num"}>{"۰۱"}</span><strong>{"اعتبار کسب‌وکار"}</strong><small>{"اعتبار تأییدشده شما در حساب B2B"}</small></div><div className={"sup-flow-step"}><span className={"sup-flow-num"}>{"۰۲"}</span><strong>{"انتخاب کالای SCF"}</strong><small>{"نشان SCF روی کارت و صفحه کالا"}</small></div><div className={"sup-flow-step"}><span className={"sup-flow-num"}>{"۰۳"}</span><strong>{"ثبت سفارش"}</strong><small>{"استفاده از اعتبار بدون پرداخت اولیه در لحظه سفارش*"}</small></div></div><div className={"sup-panel-foot"}><span>{"* درصد پوشش و شرایط نهایی از قرارداد و اعتبار واقعی دریافت می‌شود."}</span><strong>{"SCF ≠ BNPL مصرف‌کننده"}</strong></div></div></div></div></section>
<div className={"sup-stat-strip"}><div className={"container-xl px-3"}><div className={"sup-stat-grid"}><div className={"sup-stat"}><strong>{"۱۵۱۸+ قلم"}</strong><span>{"اقلام نمونه در شبکه تأمین"}</span></div><div className={"sup-stat"}><strong>{"۶ مدل تأمین‌کننده"}</strong><span>{"تولید، واردات، توزیع و عمده"}</span></div><div className={"sup-stat"}><strong>{"نقدی + آنلاین"}</strong><span>{"روش پایه تسویه سفارش"}</span></div><div className={"sup-stat"}><strong>{"SCF منتخب"}</strong><span>{"اعتبار فقط برای کالاهای نشان‌دار"}</span></div></div></div></div>
<section className={"sup-section"} id={"supplier-list"}><div className={"container-xl px-3"}><div className={"sup-section-head"}><div><h2>{"شرکت‌ها و شبکه تأمین"}</h2><p>{"مقایسه بر اساس نقش شرکت، حوزه فعالیت، تعداد اقلام، تنوع و برندهای قابل عرضه."}</p></div><div className={"sup-note"}>{"نام شرکت‌ها، قیمت‌ها و برندهای این نسخه داده نمایشی Front-end هستند و برای اتصال به دیتابیس واقعی آماده شده‌اند."}</div></div><div className={"sup-toolbar"}><button className={"sup-filter active"} data-sector={"all"} type={"button"}>{"همه حوزه‌ها"}</button><button className={"sup-filter"} data-sector={"دندانپزشکی"} type={"button"}>{"دندانپزشکی"}</button><button className={"sup-filter"} data-sector={"سلامت"} type={"button"}>{"سلامت"}</button><button className={"sup-filter"} data-sector={"زیبایی"} type={"button"}>{"زیبایی"}</button><button className={"sup-filter"} data-sector={"تندرستی"} type={"button"}>{"تندرستی"}</button><button className={"sup-filter"} data-sector={"مصرفی و بهداشتی"} type={"button"}>{"مصرفی"}</button><button className={"sup-filter scf"} data-scf-filter={""} type={"button"}>{"فقط دارای SCF"}</button></div><div className={"sup-supplier-grid"}><article className={"sup-company-card"} data-scf={"1"} data-search={"آریا دنتال تجهیز واردکننده و توزیع‌کننده دندانپزشکی dentmax global oraltech finodent"} data-sector={"دندانپزشکی"}>
<div className={"sup-company-top"}><div className={"sup-company-mark"}>{"ADT"}</div><div><h3>{"آریا دنتال تجهیز"}</h3><div className={"sup-company-role"}>{"واردکننده و توزیع‌کننده · تهران"}</div></div></div>
<span className={"sup-company-sector"}>{"دندانپزشکی · برندهای جهانی و داخلی"}</span>
<div className={"sup-company-metrics"}><div className={"sup-company-metric"}><strong>{"۱۸۸ قلم"}</strong><span>{"کالای قابل سفارش"}</span></div><div className={"sup-company-metric"}><strong>{"۱۴ گروه"}</strong><span>{"تنوع کاتالوگ"}</span></div></div>
<div className={"sup-brand-label"}>{"برندهای نمایش‌داده‌شده در کاتالوگ نمونه"}</div><div className={"sup-brand-list"}><span className={"sup-brand-chip"}>{"DentMax Global"}</span><span className={"sup-brand-chip"}>{"OralTech"}</span><span className={"sup-brand-chip"}>{"Finodent"}</span></div>
<div className={"sup-company-pay"}><div className={"sup-pay-types"}><span className={"sup-pay-pill"}>{"نقدی"}</span><span className={"sup-pay-pill"}>{"آنلاین"}</span><span className={"sup-pay-pill scf"}>{"SCF"}</span></div><span className={"sup-company-role"}>{"ارسال سراسری ۱ تا ۴ روز کاری"}</span></div></article><article className={"sup-company-card"} data-scf={"1"} data-search={"پارس کلینیک کالا تولیدکننده و تأمین‌کننده عمده سلامت parsmed nikancare clinicpro"} data-sector={"سلامت"}>
<div className={"sup-company-top"}><div className={"sup-company-mark"}>{"PCK"}</div><div><h3>{"پارس کلینیک کالا"}</h3><div className={"sup-company-role"}>{"تولیدکننده و تأمین‌کننده عمده · البرز"}</div></div></div>
<span className={"sup-company-sector"}>{"سلامت · تمرکز بر برندهای داخلی"}</span>
<div className={"sup-company-metrics"}><div className={"sup-company-metric"}><strong>{"۳۲۶ قلم"}</strong><span>{"کالای قابل سفارش"}</span></div><div className={"sup-company-metric"}><strong>{"۲۲ گروه"}</strong><span>{"تنوع کاتالوگ"}</span></div></div>
<div className={"sup-brand-label"}>{"برندهای نمایش‌داده‌شده در کاتالوگ نمونه"}</div><div className={"sup-brand-list"}><span className={"sup-brand-chip"}>{"PARSmed"}</span><span className={"sup-brand-chip"}>{"NikanCare"}</span><span className={"sup-brand-chip"}>{"ClinicPro"}</span></div>
<div className={"sup-company-pay"}><div className={"sup-pay-types"}><span className={"sup-pay-pill"}>{"نقدی"}</span><span className={"sup-pay-pill"}>{"آنلاین"}</span><span className={"sup-pay-pill scf"}>{"SCF"}</span></div><span className={"sup-company-role"}>{"تحویل عمده ۱ تا ۳ روز کاری"}</span></div></article><article className={"sup-company-card"} data-scf={"1"} data-search={"نیکا بیوتی پرو واردکننده و عمده‌فروش زیبایی dermalab skintech nikapro"} data-sector={"زیبایی"}>
<div className={"sup-company-top"}><div className={"sup-company-mark"}>{"NBP"}</div><div><h3>{"نیکا بیوتی پرو"}</h3><div className={"sup-company-role"}>{"واردکننده و عمده‌فروش · تهران"}</div></div></div>
<span className={"sup-company-sector"}>{"زیبایی · برندهای جهانی و داخلی"}</span>
<div className={"sup-company-metrics"}><div className={"sup-company-metric"}><strong>{"۲۴۱ قلم"}</strong><span>{"کالای قابل سفارش"}</span></div><div className={"sup-company-metric"}><strong>{"۱۸ گروه"}</strong><span>{"تنوع کاتالوگ"}</span></div></div>
<div className={"sup-brand-label"}>{"برندهای نمایش‌داده‌شده در کاتالوگ نمونه"}</div><div className={"sup-brand-list"}><span className={"sup-brand-chip"}>{"DermaLab"}</span><span className={"sup-brand-chip"}>{"SkinTech"}</span><span className={"sup-brand-chip"}>{"NikaPro"}</span></div>
<div className={"sup-company-pay"}><div className={"sup-pay-types"}><span className={"sup-pay-pill"}>{"نقدی"}</span><span className={"sup-pay-pill"}>{"آنلاین"}</span><span className={"sup-pay-pill scf"}>{"SCF"}</span></div><span className={"sup-company-role"}>{"ارسال سریع تهران و شهرستان"}</span></div></article><article className={"sup-company-card"} data-scf={"0"} data-search={"زیست سلامت تجهیز توزیع‌کننده تجهیزات حرفه‌ای سلامت vitalone medscope zistmed"} data-sector={"سلامت"}>
<div className={"sup-company-top"}><div className={"sup-company-mark"}>{"ZHT"}</div><div><h3>{"زیست سلامت تجهیز"}</h3><div className={"sup-company-role"}>{"توزیع‌کننده تجهیزات حرفه‌ای · اصفهان"}</div></div></div>
<span className={"sup-company-sector"}>{"سلامت · برندهای جهانی و داخلی"}</span>
<div className={"sup-company-metrics"}><div className={"sup-company-metric"}><strong>{"۱۵۴ قلم"}</strong><span>{"کالای قابل سفارش"}</span></div><div className={"sup-company-metric"}><strong>{"۱۱ گروه"}</strong><span>{"تنوع کاتالوگ"}</span></div></div>
<div className={"sup-brand-label"}>{"برندهای نمایش‌داده‌شده در کاتالوگ نمونه"}</div><div className={"sup-brand-list"}><span className={"sup-brand-chip"}>{"VitalOne"}</span><span className={"sup-brand-chip"}>{"MedScope"}</span><span className={"sup-brand-chip"}>{"ZistMed"}</span></div>
<div className={"sup-company-pay"}><div className={"sup-pay-types"}><span className={"sup-pay-pill"}>{"نقدی"}</span><span className={"sup-pay-pill"}>{"آنلاین"}</span></div><span className={"sup-company-role"}>{"۲ تا ۵ روز کاری"}</span></div></article><article className={"sup-company-card"} data-scf={"1"} data-search={"آوان فیت تجهیز واردکننده و توزیع‌کننده تندرستی fitcore rehabx avanfit"} data-sector={"تندرستی"}>
<div className={"sup-company-top"}><div className={"sup-company-mark"}>{"AFT"}</div><div><h3>{"آوان فیت تجهیز"}</h3><div className={"sup-company-role"}>{"واردکننده و توزیع‌کننده · تهران"}</div></div></div>
<span className={"sup-company-sector"}>{"تندرستی · برندهای جهانی و داخلی"}</span>
<div className={"sup-company-metrics"}><div className={"sup-company-metric"}><strong>{"۱۲۹ قلم"}</strong><span>{"کالای قابل سفارش"}</span></div><div className={"sup-company-metric"}><strong>{"۹ گروه"}</strong><span>{"تنوع کاتالوگ"}</span></div></div>
<div className={"sup-brand-label"}>{"برندهای نمایش‌داده‌شده در کاتالوگ نمونه"}</div><div className={"sup-brand-list"}><span className={"sup-brand-chip"}>{"FitCore"}</span><span className={"sup-brand-chip"}>{"RehabX"}</span><span className={"sup-brand-chip"}>{"AvanFit"}</span></div>
<div className={"sup-company-pay"}><div className={"sup-pay-types"}><span className={"sup-pay-pill"}>{"نقدی"}</span><span className={"sup-pay-pill"}>{"آنلاین"}</span><span className={"sup-pay-pill scf"}>{"SCF"}</span></div><span className={"sup-company-role"}>{"۲ تا ۶ روز کاری"}</span></div></article><article className={"sup-company-card"} data-scf={"0"} data-search={"سپهر مصرف سلامت تولیدکننده و عمده‌فروش مصرفی و بهداشتی sepehrcare mediroll safetouch"} data-sector={"مصرفی و بهداشتی"}>
<div className={"sup-company-top"}><div className={"sup-company-mark"}>{"SMS"}</div><div><h3>{"سپهر مصرف سلامت"}</h3><div className={"sup-company-role"}>{"تولیدکننده و عمده‌فروش · قزوین"}</div></div></div>
<span className={"sup-company-sector"}>{"مصرفی و بهداشتی · برندهای داخلی"}</span>
<div className={"sup-company-metrics"}><div className={"sup-company-metric"}><strong>{"۴۸۰ قلم"}</strong><span>{"کالای قابل سفارش"}</span></div><div className={"sup-company-metric"}><strong>{"۳۱ گروه"}</strong><span>{"تنوع کاتالوگ"}</span></div></div>
<div className={"sup-brand-label"}>{"برندهای نمایش‌داده‌شده در کاتالوگ نمونه"}</div><div className={"sup-brand-list"}><span className={"sup-brand-chip"}>{"SepehrCare"}</span><span className={"sup-brand-chip"}>{"MediRoll"}</span><span className={"sup-brand-chip"}>{"SafeTouch"}</span></div>
<div className={"sup-company-pay"}><div className={"sup-pay-types"}><span className={"sup-pay-pill"}>{"نقدی"}</span><span className={"sup-pay-pill"}>{"آنلاین"}</span></div><span className={"sup-company-role"}>{"ارسال کارتن و پالت ۱ تا ۳ روز کاری"}</span></div></article></div></div></section>
<section className={"sup-section soft"} id={"supplier-products"}><div className={"container-xl px-3"}><div className={"sup-section-head"}><div><h2>{"کاتالوگ خرید عمده"}</h2><p>{"هر کالا صفحه اختصاصی، کد SKU، موجودی، حداقل سفارش، قیمت پلکانی و شرایط تسویه دارد."}</p></div></div><div className={"sup-catalog-layout"}><aside className={"sup-side"}><h3>{"فیلتر خرید عمده"}</h3><div className={"sup-side-group"}><label><span><input data-scf-check={""} type={"checkbox"} />{" فقط کالاهای SCF"}</span><b>{"اعتباری"}</b></label></div><div className={"sup-side-group"}><div className={"sup-note"}>{"روش‌های تسویه"}</div><label><span>{"نقدی"}</span><b>{"همه کالاها"}</b></label><label><span>{"آنلاین"}</span><b>{"همه کالاها"}</b></label><label><span>{"SCF"}</span><b>{"منتخب"}</b></label></div><div className={"sup-side-group"}><div className={"sup-note"}>{"قاعده SCF"}</div><p className={"sup-note mb-0"}>{"اگر بج SCF روی کالا وجود نداشته باشد، آن کالا از اعتبار زنجیره تأمین قابل خرید نیست."}</p></div></aside><div><div className={"sup-result-head"}><div className={"sup-result-count"} data-result-count={""}><strong>{"۱۲"}</strong>{" کالا"}</div><select aria-label={"مرتب‌سازی کالاهای عمده"} className={"sup-sort"} data-sort={""} name={"sort"}><option value={"default"}>{"پیشنهادی"}</option><option value={"price-asc"}>{"ارزان‌ترین"}</option><option value={"price-desc"}>{"گران‌ترین"}</option><option value={"stock"}>{"بیشترین موجودی"}</option></select></div><div className={"sup-product-grid"}><article className={"sup-product-card"} data-price={"428000000"} data-scf={"1"} data-search={"یونیت دندانپزشکی finodent ax7 den-unit-ax7 finodent دندانپزشکی آریا دنتال تجهیز"} data-sector={"دندانپزشکی"} data-stock={"18"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/dental-unit.avif"} type={"image/avif"} /><img alt={"یونیت دندانپزشکی Finodent AX7"} decoding={"async"} fetchPriority={"high"} height={"1000"} src={"/assets/images/suppliers/dental-unit.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند داخلی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"آریا دنتال تجهیز · واردکننده و توزیع‌کننده"}</div><h3 className={"sup-prod-title"}>{"یونیت دندانپزشکی Finodent AX7"}</h3><div className={"sup-prod-sku"}>{"SKU: DEN-UNIT-AX7"}</div><div className={"sup-prod-stock"}><span>{"۱۸ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"428٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"455٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-den-unit-ax7"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"DEN-UNIT-AX7"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"198000000"} data-scf={"1"} data-search={"اتوکلاو کلاس b ظرفیت ۲۳ لیتر den-auto-b23 dentmax global دندانپزشکی آریا دنتال تجهیز"} data-sector={"دندانپزشکی"} data-stock={"26"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/autoclave.avif"} type={"image/avif"} /><img alt={"اتوکلاو کلاس B ظرفیت ۲۳ لیتر"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/autoclave.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند جهانی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"آریا دنتال تجهیز · واردکننده و توزیع‌کننده"}</div><h3 className={"sup-prod-title"}>{"اتوکلاو کلاس B ظرفیت ۲۳ لیتر"}</h3><div className={"sup-prod-sku"}>{"SKU: DEN-AUTO-B23"}</div><div className={"sup-prod-stock"}><span>{"۲۶ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"198٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"212٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-den-auto-b23"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"DEN-AUTO-B23"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"47500000"} data-scf={"1"} data-search={"اسکیلر اولتراسونیک oraltech u6 den-scaler-u6 oraltech دندانپزشکی آریا دنتال تجهیز"} data-sector={"دندانپزشکی"} data-stock={"64"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/scaler.avif"} type={"image/avif"} /><img alt={"اسکیلر اولتراسونیک OralTech U6"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/scaler.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند جهانی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"آریا دنتال تجهیز · واردکننده و توزیع‌کننده"}</div><h3 className={"sup-prod-title"}>{"اسکیلر اولتراسونیک OralTech U6"}</h3><div className={"sup-prod-sku"}>{"SKU: DEN-SCALER-U6"}</div><div className={"sup-prod-stock"}><span>{"۶۴ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"47٬500٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"52٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-den-scaler-u6"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"DEN-SCALER-U6"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"126000000"} data-scf={"1"} data-search={"تخت معاینه برقی clinicpro e4 med-bed-e4 clinicpro سلامت پارس کلینیک کالا"} data-sector={"سلامت"} data-stock={"31"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/exam-bed.avif"} type={"image/avif"} /><img alt={"تخت معاینه برقی ClinicPro E4"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/exam-bed.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند داخلی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"پارس کلینیک کالا · تولیدکننده و تأمین‌کننده عمده"}</div><h3 className={"sup-prod-title"}>{"تخت معاینه برقی ClinicPro E4"}</h3><div className={"sup-prod-sku"}>{"SKU: MED-BED-E4"}</div><div className={"sup-prod-stock"}><span>{"۳۱ تخت موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"126٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"134٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-med-bed-e4"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"MED-BED-E4"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"289000000"} data-scf={"0"} data-search={"مانیتور علائم حیاتی vitalone v8 med-mon-v8 vitalone سلامت زیست سلامت تجهیز"} data-sector={"سلامت"} data-stock={"12"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/monitor.avif"} type={"image/avif"} /><img alt={"مانیتور علائم حیاتی VitalOne V8"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/monitor.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge brand"}>{"برند جهانی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"زیست سلامت تجهیز · توزیع‌کننده تجهیزات حرفه‌ای"}</div><h3 className={"sup-prod-title"}>{"مانیتور علائم حیاتی VitalOne V8"}</h3><div className={"sup-prod-sku"}>{"SKU: MED-MON-V8"}</div><div className={"sup-prod-stock"}><span>{"۱۲ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"289٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"299٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-med-mon-v8"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"MED-MON-V8"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"2150000"} data-scf={"0"} data-search={"رول ملحفه یکبارمصرف ۸۰ سانتی mediroll med-roll-80 mediroll مصرفی و بهداشتی سپهر مصرف سلامت"} data-sector={"مصرفی و بهداشتی"} data-stock={"860"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/roll.avif"} type={"image/avif"} /><img alt={"رول ملحفه یکبارمصرف ۸۰ سانتی MediRoll"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/roll.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge brand"}>{"برند داخلی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"سپهر مصرف سلامت · تولیدکننده و عمده‌فروش"}</div><h3 className={"sup-prod-title"}>{"رول ملحفه یکبارمصرف ۸۰ سانتی MediRoll"}</h3><div className={"sup-prod-sku"}>{"SKU: MED-ROLL-80"}</div><div className={"sup-prod-stock"}><span>{"۸۶۰ کارتن ۱۲ رول موجود"}</span><span>{"حداقل سفارش: ۲"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"2٬150٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"2٬350٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-med-roll-80"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"MED-ROLL-80"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"1480000000"} data-scf={"1"} data-search={"دستگاه لیزر دایود dermalab d1200 bty-las-d1200 dermalab زیبایی نیکا بیوتی پرو"} data-sector={"زیبایی"} data-stock={"7"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/laser.avif"} type={"image/avif"} /><img alt={"دستگاه لیزر دایود DermaLab D1200"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/laser.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند جهانی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"نیکا بیوتی پرو · واردکننده و عمده‌فروش"}</div><h3 className={"sup-prod-title"}>{"دستگاه لیزر دایود DermaLab D1200"}</h3><div className={"sup-prod-sku"}>{"SKU: BTY-LAS-D1200"}</div><div className={"sup-prod-stock"}><span>{"۷ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"1٬480٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"1٬560٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-bty-las-d1200"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"BTY-LAS-D1200"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"172000000"} data-scf={"1"} data-search={"تخت زیبایی برقی nikapro p5 bty-bed-p5 nikapro زیبایی نیکا بیوتی پرو"} data-sector={"زیبایی"} data-stock={"23"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/beauty-bed.avif"} type={"image/avif"} /><img alt={"تخت زیبایی برقی NikaPro P5"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/beauty-bed.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند داخلی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"نیکا بیوتی پرو · واردکننده و عمده‌فروش"}</div><h3 className={"sup-prod-title"}>{"تخت زیبایی برقی NikaPro P5"}</h3><div className={"sup-prod-sku"}>{"SKU: BTY-BED-P5"}</div><div className={"sup-prod-stock"}><span>{"۲۳ تخت موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"172٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"184٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-bty-bed-p5"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"BTY-BED-P5"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"386000000"} data-scf={"1"} data-search={"آنالایزر پوست skintech ai10 bty-skin-ai10 skintech زیبایی نیکا بیوتی پرو"} data-sector={"زیبایی"} data-stock={"9"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/skin-analyzer.avif"} type={"image/avif"} /><img alt={"آنالایزر پوست SkinTech AI10"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/skin-analyzer.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند جهانی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"نیکا بیوتی پرو · واردکننده و عمده‌فروش"}</div><h3 className={"sup-prod-title"}>{"آنالایزر پوست SkinTech AI10"}</h3><div className={"sup-prod-sku"}>{"SKU: BTY-SKIN-AI10"}</div><div className={"sup-prod-stock"}><span>{"۹ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"386٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"415٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-bty-skin-ai10"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"BTY-SKIN-AI10"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"690000000"} data-scf={"1"} data-search={"تردمیل تجاری fitcore x9 wel-tread-x9 fitcore تندرستی آوان فیت تجهیز"} data-sector={"تندرستی"} data-stock={"14"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/treadmill.avif"} type={"image/avif"} /><img alt={"تردمیل تجاری FitCore X9"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/treadmill.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند جهانی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"آوان فیت تجهیز · واردکننده و توزیع‌کننده"}</div><h3 className={"sup-prod-title"}>{"تردمیل تجاری FitCore X9"}</h3><div className={"sup-prod-sku"}>{"SKU: WEL-TREAD-X9"}</div><div className={"sup-prod-stock"}><span>{"۱۴ دستگاه موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"690٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"725٬000٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-wel-tread-x9"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"WEL-TREAD-X9"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"78000000"} data-scf={"1"} data-search={"تخت ماساژ حرفه‌ای avanfit r7 wel-mass-r7 avanfit تندرستی آوان فیت تجهیز"} data-sector={"تندرستی"} data-stock={"38"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/massage-bed.avif"} type={"image/avif"} /><img alt={"تخت ماساژ حرفه‌ای AvanFit R7"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/massage-bed.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge scf"}>{"SCF"}</span><span className={"sup-badge brand"}>{"برند داخلی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"آوان فیت تجهیز · واردکننده و توزیع‌کننده"}</div><h3 className={"sup-prod-title"}>{"تخت ماساژ حرفه‌ای AvanFit R7"}</h3><div className={"sup-prod-sku"}>{"SKU: WEL-MASS-R7"}</div><div className={"sup-prod-stock"}><span>{"۳۸ تخت موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"78٬000٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"83٬500٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span><span className={"scf"}>{"SCF · بدون پرداخت اولیه*"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-wel-mass-r7"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"WEL-MASS-R7"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article><article className={"sup-product-card"} data-price={"94500000"} data-scf={"0"} data-search={"دستکش نیتریل safetouch — سفارش عمده ۱۰,۰۰۰ عدد con-nitr-10k safetouch مصرفی و بهداشتی سپهر مصرف سلامت"} data-sector={"مصرفی و بهداشتی"} data-stock={"94"}>
<div className={"sup-prod-media"}><picture className={"beautypay-picture"}><source srcSet={"/assets/images/suppliers/gloves.avif"} type={"image/avif"} /><img alt={"دستکش نیتریل SafeTouch — سفارش عمده ۱۰,۰۰۰ عدد"} decoding={"async"} fetchPriority={"low"} height={"1000"} loading={"lazy"} src={"/assets/images/suppliers/gloves.webp"} width={"1000"} /></picture><div className={"sup-badges"}><span className={"sup-badge brand"}>{"برند داخلی"}</span></div></div>
<div className={"sup-prod-body"}><div className={"sup-prod-company"}>{"سپهر مصرف سلامت · تولیدکننده و عمده‌فروش"}</div><h3 className={"sup-prod-title"}>{"دستکش نیتریل SafeTouch — سفارش عمده ۱۰,۰۰۰ عدد"}</h3><div className={"sup-prod-sku"}>{"SKU: CON-NITR-10K"}</div><div className={"sup-prod-stock"}><span>{"۹۴ پالت/پک ۱۰,۰۰۰ عدد موجود"}</span><span>{"حداقل سفارش: ۱"}</span></div>
<div className={"sup-prod-price-label"}>{"قیمت عمده از"}</div><div><span className={"sup-prod-price"}>{"94٬500٬000 "}<small>{"تومان"}</small></span><span className={"sup-prod-old"}>{"99٬500٬000"}</span></div><div className={"sup-prod-settle"}><span>{"نقدی"}</span><span>{"آنلاین"}</span></div>
<div className={"sup-prod-action"}><a className={"sup-prod-link"} href={"/supplier-product-con-nitr-10k"}>{"مشاهده کالا و سفارش"}</a><button className={"sup-prod-code"} data-copy-sku={"CON-NITR-10K"} title={"کپی کد کالا"} type={"button"}>{"#"}</button></div></div></article></div></div></div></div></section>
<section className={"sup-section"}><div className={"container-xl px-3"}><div className={"sup-scf-explain"}><div><span className={"sup-scf-badge-lg"}>{"SCF"}</span><h2 className={"mt-3"}>{"اعتبار برای خرید کالا، نه پرداخت مصرف‌کننده."}</h2><p>{"در این بازار B2B، پرداخت اعتباری فقط از مسیر Supply Chain Finance انجام می‌شود. بنابراین صاحب کسب‌وکار با یک نگاه می‌بیند کدام کالا می‌تواند از اعتبار تأمین زنجیره استفاده کند و کدام کالا فقط نقدی یا آنلاین است."}</p></div><div className={"sup-scf-list"}><div className={"sup-scf-item"}><strong>{"نشان روی کارت کالا"}</strong><span>{"قبل از ورود به جزئیات، امکان استفاده از SCF مشخص است."}</span></div><div className={"sup-scf-item"}><strong>{"نمایش در صفحه محصول"}</strong><span>{"شرایط اعتبار کنار قیمت، موجودی و حداقل سفارش تکرار می‌شود."}</span></div><div className={"sup-scf-item"}><strong>{"قیمت عمده پلکانی"}</strong><span>{"مبلغ واحد بر اساس تعداد سفارش قابل تغییر است."}</span></div><div className={"sup-scf-item"}><strong>{"آماده اتصال به API"}</strong><span>{"اعتبار واقعی، سقف پوشش و قرارداد تأمین‌کننده بعداً از Backend دریافت می‌شود."}</span></div></div></div></div></section>
</main>
</>; }
